const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function requirements(profile,buildingId){return profile.buildings?.[buildingId]||null}
export function canStart(profile,buildingId,{inventory={},toolTier=0}={}){const b=requirements(profile,buildingId);if(!b)return false;return toolTier>=b.toolTier&&Object.entries(b.materials).every(([k,v])=>(inventory[k]||0)>=v)}
export function consumeMaterials(materials,inventory={}){const next={...inventory};for(const[k,v]of Object.entries(materials||{}))next[k]=Math.max(0,(next[k]||0)-v);return next}
export function startConstruction(profile,buildingId,ctx={}){const b=requirements(profile,buildingId);if(!b)return{ok:false,reason:'UNKNOWN_BUILDING'};if(!canStart(profile,buildingId,ctx))return{ok:false,reason:'REQUIREMENTS'};return{ok:true,inventory:consumeMaterials(b.materials,ctx.inventory),project:{buildingId,stageIndex:0,stageProgress:0,laborDone:0,complete:false,condition:1}}}
export function buildStep(profile,project,{labor=0,toolTier=0}={}){const b=requirements(profile,project?.buildingId);if(!b||project.complete)return{...project};if(toolTier<b.toolTier)return{...project,blocked:'TOOL_TIER'};const stageLabor=b.labor/b.stages.length,done=project.laborDone+Math.max(0,labor),stageIndex=Math.min(b.stages.length-1,Math.floor(done/stageLabor));const complete=done>=b.labor;return{...project,laborDone:Math.min(done,b.labor),stageIndex:complete?b.stages.length-1:stageIndex,stageProgress:complete?1:clamp((done-stageIndex*stageLabor)/stageLabor,0,1),complete,currentStage:b.stages[Math.min(stageIndex,b.stages.length-1)]}}
export function repairStructure(state,{materialsAvailable=0,labor=0}={}){const damage=1-clamp(state?.condition??1,0,1),repairPotential=Math.min(damage,materialsAvailable*.08,labor*.06);return{...state,condition:clamp((state?.condition??1)+repairPotential,0,1),materialsUsed:repairPotential/0.08,laborUsed:repairPotential/0.06}}
export function applyUpgrade(profile,state,upgradeId,{inventory={},labor=0}={}){const u=profile.upgrades?.[upgradeId];if(!u)return{ok:false,reason:'UNKNOWN_UPGRADE'};if(labor<u.labor||!Object.entries(u.materials).every(([k,v])=>(inventory[k]||0)>=v))return{ok:false,reason:'REQUIREMENTS'};return{ok:true,inventory:consumeMaterials(u.materials,inventory),structure:{...state,upgrades:[...(state?.upgrades||[]),upgradeId],bonuses:{...(state?.bonuses||{}),...Object.fromEntries(Object.entries(u.effect).map(([k,v])=>[k,(state?.bonuses?.[k]||0)+v]))}}}}
export function settlementCapacity(structures=[]){return structures.filter(s=>s.complete).reduce((a,s)=>a+(s.capacity||0),0)}
