const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export function createDebt({id,debtorId,creditorId,principal=0,interestRate=0,dueAt=0,collateral=null,originContractId=null}={}){return{id,debtorId,creditorId,principal:Math.max(0,principal),outstanding:Math.max(0,principal),interestRate:Math.max(0,interestRate),dueAt,collateral,originContractId,status:'ACTIVE',payments:[],renegotiations:0}}
export function accrueDebt(debt,{days=0}={}){if(debt.status!=='ACTIVE')return{...debt};const factor=1+Math.max(0,debt.interestRate||0)*Math.max(0,days)/365;return{...debt,outstanding:debt.outstanding*factor}}
export function recordPayment(debt,{amount=0,at=0}={}){if(!['ACTIVE','DEFAULTED','RENEGOTIATED'].includes(debt.status))return{...debt};const paid=Math.min(Math.max(0,amount),Math.max(0,debt.outstanding||0));const outstanding=Math.max(0,(debt.outstanding||0)-paid);return{...debt,outstanding,payments:[...(debt.payments||[]),{amount:paid,at}],status:outstanding<=1e-9?'SETTLED':debt.status}}
export function assessDefault(debt,{now=0,gracePeriod=0}={}){const overdue=Math.max(0,now-(debt.dueAt||0)-Math.max(0,gracePeriod));const defaulted=debt.status!=='SETTLED'&&debt.outstanding>0&&overdue>0;return{...debt,status:defaulted?'DEFAULTED':debt.status,overdue}}
export function renegotiateDebt(debt,{newDueAt,newInterestRate,principalAdjustment=0,accepted=false}={}){if(!accepted||debt.status==='SETTLED')return{...debt,renegotiationRejected:true};return{...debt,dueAt:newDueAt??debt.dueAt,interestRate:Math.max(0,newInterestRate??debt.interestRate),outstanding:Math.max(0,(debt.outstanding||0)+principalAdjustment),status:'RENEGOTIATED',renegotiations:(debt.renegotiations||0)+1,renegotiationRejected:false}}
export function forgiveDebt(debt,{amount=0,full=false,reason=''}={}){const forgiven=full?Math.max(0,debt.outstanding||0):Math.min(Math.max(0,amount),Math.max(0,debt.outstanding||0));const outstanding=Math.max(0,(debt.outstanding||0)-forgiven);return{...debt,outstanding,forgiven:(debt.forgiven||0)+forgiven,forgivenessReason:reason,status:outstanding<=1e-9?'FORGIVEN':debt.status}}
export function creditConsequence({debt,trust=.5,reliability=.5,relationship=.5}={}){const exposure=Math.min(1,Math.max(0,debt?.outstanding||0)/Math.max(1,debt?.principal||1));const defaultPenalty=debt?.status==='DEFAULTED'?0.45*exposure:0;const renegPenalty=debt?.status==='RENEGOTIATED'?0.08*Math.min(1,debt?.renegotiations||0):0;const repaymentBonus=debt?.status==='SETTLED'?0.22:0;return{trust:clamp(trust-defaultPenalty-renegPenalty+repaymentBonus),reliability:clamp(reliability-defaultPenalty*.8-renegPenalty*.6+repaymentBonus*.9),relationship:clamp(relationship-defaultPenalty*.55+repaymentBonus*.35)}}
export function debtLedger(debts=[]){const active=debts.filter(d=>['ACTIVE','RENEGOTIATED','DEFAULTED'].includes(d.status));return{activeCount:active.length,totalOutstanding:active.reduce((s,d)=>s+Math.max(0,d.outstanding||0),0),defaults:active.filter(d=>d.status==='DEFAULTED').length,settled:debts.filter(d=>d.status==='SETTLED').length,forgiven:debts.filter(d=>d.status==='FORGIVEN').length}}
