const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export function pairCompatibility({bond=.5,health=.7,resourceSecurity=.5,stress=.2,kinshipRisk=0}={}){return clamp(bond*.35+health*.25+resourceSecurity*.2+(1-stress)*.15+(1-kinshipRisk)*.05)}
export function reproductionReadiness({maturity=1,health=.7,energy=.7,pair=.5,resourceSecurity=.5,season=.5}={}){return clamp(maturity*.15+health*.2+energy*.15+pair*.2+resourceSecurity*.2+season*.1)}
export function newbornRecord({id,parentIds=[],generation=0,bornAt=0,traits={}}={}){return{id,parentIds:[...parentIds],generation,bornAt,traits:{...traits},lifeStage:'NEWBORN',alive:true}}
export function careCoverage({caregivers=[],youngCount=1,food=.5,shelter=.5,safety=.5}={}){const caregiverCapacity=caregivers.reduce((s,c)=>s+clamp((c.skill||.5)*(c.availability||.5)),0);return clamp((caregiverCapacity/Math.max(1,youngCount))*.45+food*.2+shelter*.15+safety*.2)}
export function mature(individual,{age=0,juvenileAt=10,adultAt=30,elderAt=120}={}){const lifeStage=age>=elderAt?'ELDER':age>=adultAt?'ADULT':age>=juvenileAt?'JUVENILE':'NEWBORN';return{...individual,age,lifeStage}}
export function mortalityRisk({agePressure=0,health=.8,injury=0,disease=0,starvation=0,environment=0,care=.5}={}){return clamp(agePressure*.2+(1-health)*.25+injury*.2+disease*.15+starvation*.15+environment*.1-care*.05)}
export function inheritCulture({teachers=[],groupTraditions=[]}={}){const learned=new Map();for(const t of teachers){for(const k of t.knowledge||[]){const prev=learned.get(k.id)||0;learned.set(k.id,Math.max(prev,clamp((k.strength||.5)*(t.contact||.5))));}}for(const tr of groupTraditions){const prev=learned.get(tr.id)||0;learned.set(tr.id,Math.max(prev,clamp((tr.stability||.5)*(tr.exposure||.5))));}return[...learned].map(([id,strength])=>({id,strength})).filter(x=>x.strength>.12)}
export function generationContinuity({births=0,deaths=0,juveniles=0,adults=0,elders=0,carryingCapacity=1}={}){const population=Math.max(0,juveniles+adults+elders);const growth=births-deaths;const pressure=clamp(population/Math.max(1,carryingCapacity));return{population,growth,pressure,status:growth>0&&pressure<.9?'GROWING':growth<0?'DECLINING':'STABLE'}}
