const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export function createClaim({id,assetId,assetType='ITEM',ownerId=null,custodianId=null,claimType='OWNERSHIP',strength=1,source='CREATION',at=0,scope=null}={}){return{id,assetId,assetType,ownerId,custodianId,claimType,strength:clamp(strength),source,at,scope,status:'ACTIVE',history:[{event:'CLAIM_CREATED',ownerId,custodianId,at,source}]}}
export function authorizeUse(claim,{actorId,permission='USE',expiresAt=null,at=0}={}){return{...claim,permissions:[...(claim.permissions||[]),{actorId,permission,expiresAt,at}]}}
export function canUse(claim,{actorId,permission='USE',now=0}={}){if(!claim||claim.status!=='ACTIVE')return false;if(actorId===claim.ownerId||actorId===claim.custodianId)return true;return(claim.permissions||[]).some(p=>p.actorId===actorId&&p.permission===permission&&(p.expiresAt==null||p.expiresAt>=now))}
export function transferClaim(claim,{fromId,toId,at=0,reason='TRANSFER'}={}){if(claim.status!=='ACTIVE'||claim.ownerId!==fromId||!toId)return{...claim,transferRejected:true};return{...claim,ownerId:toId,custodianId:toId,transferRejected:false,history:[...(claim.history||[]),{event:'TRANSFER',fromId,toId,at,reason}]}}
export function changeCustody(claim,{custodianId,at=0,reason='CUSTODY'}={}){if(claim.status!=='ACTIVE')return{...claim};return{...claim,custodianId,history:[...(claim.history||[]),{event:'CUSTODY_CHANGED',custodianId,at,reason}]}}
export function abandonClaim(claim,{actorId,at=0}={}){if(claim.ownerId!==actorId||claim.status!=='ACTIVE')return{...claim,abandonRejected:true};return{...claim,status:'ABANDONED',ownerId:null,custodianId:null,abandonRejected:false,history:[...(claim.history||[]),{event:'ABANDONED',actorId,at}]}}
export function contestClaims(claims=[]){const active=claims.filter(c=>c.status==='ACTIVE');const byAsset=new Map();for(const c of active){if(!byAsset.has(c.assetId))byAsset.set(c.assetId,[]);byAsset.get(c.assetId).push(c)}const out=[];for(const [assetId,list] of byAsset){const owners=[...new Set(list.map(c=>c.ownerId).filter(Boolean))];const contested=owners.length>1;const ranked=[...list].sort((a,b)=>(b.strength||0)-(a.strength||0)||((a.at||0)-(b.at||0)));out.push({assetId,contested,owners,leadingClaim:ranked[0]||null,claims:ranked});}return out}
export function resolveDispute({claims=[],evidenceByClaim={},recognizedAuthority=null}={}){const scored=claims.map(c=>{const e=evidenceByClaim[c.id]||{};const evidence=clamp(e.evidenceStrength??.5);const possession=clamp(e.possessionContinuity??.5);const witness=clamp(e.witnessConfidence??.5);const authority=recognizedAuthority&&e.authorityId===recognizedAuthority?1:clamp(e.authorityWeight??.5);const score=clamp((c.strength||0)*.3+evidence*.3+possession*.2+witness*.1+authority*.1);return{claim:c,score}}).sort((a,b)=>b.score-a.score);return{winner:scored[0]?.claim||null,score:scored[0]?.score||0,contested:scored.length>1,ranked:scored}}
export function propertyState(claims=[]){const active=claims.filter(c=>c.status==='ACTIVE');return{activeClaims:active.length,ownedAssets:new Set(active.filter(c=>c.ownerId).map(c=>c.assetId)).size,abandonedAssets:new Set(claims.filter(c=>c.status==='ABANDONED').map(c=>c.assetId)).size,contestedAssets:contestClaims(claims).filter(c=>c.contested).length}}
