const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function generationOutput(source={}){const availability=clamp(source.availability??1,0,1);const condition=clamp(source.condition??1,0,1);const fuelFactor=source.fuelRequired?clamp((source.fuelLiters||0)/Math.max(0.0001,source.fuelNominalLiters||1),0,1):1;return Math.max(0,(source.maxKw||0)*availability*condition*fuelFactor)}
export function batteryState(battery={},netKw=0,hours=1){const cap=Math.max(0,battery.capacityKwh||0);const current=clamp(battery.chargeKwh||0,0,cap);const eff=clamp(battery.efficiency??.92,.1,1);const delta=netKw>=0?netKw*hours*eff:netKw*hours/eff;const charge=clamp(current+delta,0,cap);return{...battery,chargeKwh:charge,stateOfCharge:cap?charge/cap:0}}
export function dispatchLoads(loads=[],availableKw=0){const sorted=[...loads].sort((a,b)=>(b.priority||0)-(a.priority||0));let remaining=Math.max(0,availableKw);const dispatched=[];for(const load of sorted){const demand=Math.max(0,load.demandKw||0);const supplied=Math.min(demand,remaining);remaining-=supplied;dispatched.push({...load,suppliedKw:supplied,online:supplied>=demand*(load.minServiceFraction??1),serviceFraction:demand?supplied/demand:1});}return{dispatched,unusedKw:remaining,servedKw:Math.max(0,availableKw)-remaining}}
export function utilityTick({sources=[],battery=null,loads=[],hours=1}={}){const generatedKw=sources.reduce((sum,s)=>sum+generationOutput(s),0);const demandKw=loads.reduce((sum,l)=>sum+Math.max(0,l.demandKw||0),0);let availableKw=generatedKw;let nextBattery=battery;
if(battery){const cap=Math.max(0,battery.capacityKwh||0);const current=clamp(battery.chargeKwh||0,0,cap);if(generatedKw>demandKw){nextBattery=batteryState(battery,generatedKw-demandKw,hours);availableKw=demandKw;}else if(generatedKw<demandKw&&current>0){const maxDischargeKw=Math.min(battery.maxDischargeKw||Infinity,current/Math.max(hours,.0001));const deficit=demandKw-generatedKw;const discharge=Math.min(deficit,maxDischargeKw);nextBattery=batteryState(battery,-discharge,hours);availableKw+=discharge;}}
const dispatch=dispatchLoads(loads,availableKw);return{generatedKw,demandKw,battery:nextBattery,...dispatch,brownout:dispatch.dispatched.some(x=>!x.online)}}
export function consumeFuel(source={},hours=1){if(!source.fuelRequired)return source;const burn=Math.max(0,source.fuelBurnLitersPerHour||0)*Math.max(0,hours);return{...source,fuelLiters:Math.max(0,(source.fuelLiters||0)-burn)}}
export function maintenanceNeed(asset={}){const condition=clamp(asset.condition??1,0,1);const criticality=clamp(asset.criticality??.5,0,1);const hours=Math.max(0,asset.runtimeHours||0);return clamp((1-condition)*.6+Math.min(1,hours/1000)*.25+criticality*.15,0,1)}
