const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function forecastDemand({history=[],horizonDays=7,trend=0}={}){if(!history.length)return{daily:0,horizon:0};const avg=history.reduce((a,b)=>a+b,0)/history.length;const daily=Math.max(0,avg+trend);return{daily,horizon:daily*horizonDays}}
export function reorderPoint({dailyDemand=0,leadTimeDays=0,safetyStock=0}={}){return Math.max(0,dailyDemand*leadTimeDays+safetyStock)}
export function inventoryPosition({onHand=0,onOrder=0,backorders=0}={}){return Math.max(0,onHand+onOrder-backorders)}
export function replenishmentNeed({inventory={},policy={},forecast={}}={}){const daily=forecast.daily??policy.dailyDemand??0;const rop=reorderPoint({dailyDemand:daily,leadTimeDays:policy.leadTimeDays||0,safetyStock:policy.safetyStock||0});const position=inventoryPosition(inventory);const target=Math.max(rop,policy.targetStock||0);return{reorderPoint:rop,position,target,required:position<=rop?Math.max(0,target-position):0,status:position<=rop?'REPLENISH':'OK'}}
export function supplierScore({reliability=.5,leadTimeDays=7,costIndex=1,trust=.5,capacity=1,risk=.5}={}){return clamp(reliability*.3+trust*.2+capacity*.2+(1-clamp(risk,0,1))*.15+(1/(1+Math.max(0,leadTimeDays)))*.1+(1/(1+Math.max(.01,costIndex)))*.05,0,1)}
export function chooseSupplier(suppliers=[]){return [...suppliers].map(s=>({...s,score:supplierScore(s)})).sort((a,b)=>b.score-a.score)[0]||null}
export function planProcurement({items=[],suppliersByItem={},budget=Infinity,transportCapacity=Infinity}={}){let spent=0,volume=0;const orders=[];const shortages=[];for(const item of items.sort((a,b)=>(b.priority||0)-(a.priority||0))){const need=replenishmentNeed(item);if(!need.required)continue;const supplier=chooseSupplier(suppliersByItem[item.id]||[]);if(!supplier){shortages.push({itemId:item.id,reason:'NO_SUPPLIER'});continue;}const unitCost=supplier.unitCost||0,unitVolume=item.unitVolume||1;const maxBudget=unitCost?Math.floor((budget-spent)/unitCost):need.required;const maxTransport=Math.floor((transportCapacity-volume)/unitVolume);const qty=Math.max(0,Math.min(need.required,maxBudget,maxTransport,supplier.availableQty??need.required));if(qty<=0){shortages.push({itemId:item.id,reason:'CAPACITY_OR_BUDGET'});continue;}orders.push({itemId:item.id,supplierId:supplier.id,quantity:qty,unitCost,etaDays:supplier.leadTimeDays||0,priority:item.priority||0});spent+=qty*unitCost;volume+=qty*unitVolume;if(qty<need.required)shortages.push({itemId:item.id,reason:'PARTIAL',remaining:need.required-qty});}return{orders,shortages,spent,usedTransportCapacity:volume}}
export function stockoutRisk({position=0,dailyDemand=0,leadTimeDays=0,safetyStock=0}={}){const expected=dailyDemand*leadTimeDays;return clamp((expected+safetyStock-position)/Math.max(1,expected+safetyStock),0,1)}
