const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function careNeed(profile,speciesId,{days=1}={}){const s=profile.species?.[speciesId];if(!s)return null;return{feed:s.feedNeed*days,water:s.waterNeed*days}}
export function feedAnimal(profile,state,{speciesId,feedId='FORAGE',amount=0,water=0,shelter=.5}={}){const s=profile.species?.[speciesId],f=profile.feeds?.[feedId];if(!s||!f)return{...state};const feedSat=clamp(amount/Math.max(.01,s.feedNeed),0,1),waterSat=clamp(water/Math.max(.01,s.waterNeed),0,1);const nutrition=feedSat*f.nutrition,healthGain=(nutrition*.42+waterSat*.38+clamp(shelter,0,1)*.20)*.10;const tameness=clamp((state?.tameness??.1)+s.tamenessGain*(feedSat*.5+waterSat*.3+shelter*.2),0,1);return{...state,feedSat,waterSat,health:clamp((state?.health??.7)+healthGain-(1-feedSat)*.05-(1-waterSat)*.06,0,1),tameness}}
export function livestockDay(profile,state,{speciesId,shelter=.5,diseasePressure=0,days=1}={}){const s=profile.species?.[speciesId];if(!s)return{...state};const fed=state?.feedSat??0,water=state?.waterSat??0;const stress=(1-fed)*.06+(1-water)*.08+(1-shelter)*.04+diseasePressure*.08;const health=clamp((state?.health??.7)-stress*days+.02*shelter*days,0,1);return{...state,day:(state?.day||0)+days,ageDays:(state?.ageDays||0)+days,health,feedSat:clamp(fed-days*.55,0,1),waterSat:clamp(water-days*.65,0,1)}}
export function canBreed(profile,a,b,{speciesId}={}){const s=profile.species?.[speciesId];if(!s)return false;return(a?.mature&&b?.mature&&(a.health??0)>=.65&&(b.health??0)>=.65&&(a.tameness??0)>=s.breedingThreshold&&(b.tameness??0)>=s.breedingThreshold)}
export function breed(profile,a,b,{speciesId}={}){if(!canBreed(profile,a,b,{speciesId}))return{ok:false,reason:'BREEDING_REQUIREMENTS'};const s=profile.species[speciesId];return{ok:true,pregnancy:{speciesId,daysRemaining:s.gestationDays||1,health:clamp(((a.health??.7)+(b.health??.7))/2,0,1)}}}
export function dailyProducts(profile,state,{speciesId}={}){const s=profile.species?.[speciesId];if(!s)return{};const quality=clamp((state?.health??0)*.55+(state?.feedSat??0)*.25+(state?.waterSat??0)*.20,0,1),out={};for(const[id,rate]of Object.entries(s.products||{}))if(!['MEAT','HIDE'].includes(id))out[id]=rate*quality;return out}
export function slaughter(profile,state,{speciesId}={}){const s=profile.species?.[speciesId];if(!s||state?.removed)return{ok:false};const quality=clamp(state?.health??.5,.2,1),products={};for(const[id,rate]of Object.entries(s.products||{}))if(['MEAT','HIDE'].includes(id))products[id]=rate*quality;return{ok:true,removed:true,products}}
export function manureFertility(products={}){return clamp((products.MANURE||0)*.18,0,.25)}
