const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mid=a=>(a[0]+a[1])*.5;
function rangeSuit(v,[a,b]){if(v<a)return clamp(1-(a-v)/Math.max(.001,a),0,1);if(v>b)return clamp(1-(v-b)/Math.max(.001,b),0,1);return 1}
export function speciesProfile(profile,id){return profile.species?.[id]||null}
export function habitatProfile(profile,id){return profile.habitats?.[id]||{carryingCapacity:.5,foodDensity:.5,cover:.5}}
export function habitatSuitability(profile,speciesId,{depth=1,current=.1,turbidity=.2,habitat='CLEAR_LAKE'}={}){const s=speciesProfile(profile,speciesId),h=habitatProfile(profile,habitat);if(!s)return 0;const d=rangeSuit(depth,s.preferredDepth),c=rangeSuit(current,s.preferredCurrent),t=turbidity<=s.turbidityMax?1:clamp(1-(turbidity-s.turbidityMax)*1.8,0,1);return clamp((d*.34+c*.24+t*.18+h.foodDensity*.14+h.cover*.10)*h.carryingCapacity,0,1.25)}
export function fishIntent(profile,speciesId,{position={x:0,y:0,z:0},player={x:99,y:99,z:99},depth=1,current=.1,currentDir={x:0,z:1},turbidity=.2,habitat='CLEAR_LAKE',schoolCenter=null,home=null}={}){const s=speciesProfile(profile,speciesId);if(!s)return{mode:'IDLE',target:position};const dx=player.x-position.x,dy=player.y-position.y,dz=player.z-position.z,pdist=Math.hypot(dx,dy,dz),fearRadius=2.5+s.fear*7.5,territoryRadius=3+s.territorial*8;if(pdist<fearRadius&&s.fear>=s.territorial){const inv=1/Math.max(.001,pdist);return{mode:'FLEE',target:{x:position.x-dx*inv*4,y:position.y-dy*inv*1.2,z:position.z-dz*inv*4},urgency:clamp(1-pdist/fearRadius,0,1)}}if(home&&s.territorial>.6&&pdist<territoryRadius)return{mode:'DEFEND',target:{...player},urgency:clamp(1-pdist/territoryRadius,0,1)};if(s.behavior==='SCHOOL'&&schoolCenter)return{mode:'SCHOOL',target:{x:schoolCenter.x+currentDir.x*.6,y:mid(s.preferredDepth),z:schoolCenter.z+currentDir.z*.6},urgency:.55};if(s.behavior==='BOTTOM')return{mode:'FORAGE_BOTTOM',target:{x:position.x+1.2,y:Math.max(.15,mid(s.preferredDepth)*.22),z:position.z+.8},urgency:.35};return{mode:'FORAGE',target:{x:position.x+currentDir.x*(1+current),y:mid(s.preferredDepth),z:position.z+currentDir.z*(1+current)},urgency:.3}}
export function schoolingStep(members,{cohesion=.42,separation=.38,alignment=.34}={}){if(!members.length)return[];const center=members.reduce((a,m)=>({x:a.x+m.x,y:a.y+m.y,z:a.z+m.z}),{x:0,y:0,z:0});center.x/=members.length;center.y/=members.length;center.z/=members.length;return members.map(m=>{let sx=0,sy=0,sz=0;for(const n of members){if(n===m)continue;const dx=m.x-n.x,dy=m.y-n.y,dz=m.z-n.z,d=Math.hypot(dx,dy,dz);if(d<1.2&&d>.001){sx+=dx/d;sy+=dy/d;sz+=dz/d}}return{id:m.id,steer:{x:(center.x-m.x)*cohesion+sx*separation,y:(center.y-m.y)*cohesion*.4+sy*separation,z:(center.z-m.z)*cohesion+sz*separation},alignment}})}
export function populationTarget(profile,speciesId,habitatId,suitability){const s=speciesProfile(profile,speciesId),h=habitatProfile(profile,habitatId);if(!s)return 0;const avg=(s.schoolSize[0]+s.schoolSize[1])*.5;return Math.max(0,Math.round(avg*h.carryingCapacity*clamp(suitability,0,1.25)))}
